# Generated by Django 5.0.6 on 2024-07-02 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)])),
                ('model', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)])),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)])),
                ('engine', models.FloatField()),
                ('fuel', models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('Gas', 'Gas'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('Hydrogen', 'Hydrogen')], max_length=20)),
                ('body_type', models.CharField(choices=[('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Station', 'Station'), ('Wagon', 'Wagon'), ('Coupe', 'Coupe'), ('Convertibl', 'Convertible'), ('Roadster', 'Roadster'), ('Crossover', 'Crossover'), ('SUV', 'Suv'), ('Pickup', 'Pickup'), ('Truck', 'Truck'), ('Van', 'Van'), ('Minivan', 'Minivan'), ('Limousine', 'Limousine'), ('Fastback', 'Fastback'), ('Liftback', 'Liftback')], max_length=20)),
                ('drive', models.CharField(choices=[('FrontWheel', 'Frontwheel'), ('RearWheel', 'Rearwheel'), ('AllWheel', 'Allwheel'), ('FourWheel', 'Fourwheel')], max_length=20)),
                ('gearbox', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('Variable', 'Variable'), ('Automated Manual', 'Automatedmanual'), ('Sequential Transmission', 'Sequentialtransmission')], max_length=23)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000000)])),
                ('info', models.TextField(validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(180)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cars',
                'ordering': ('id',),
            },
        ),
    ]
