# Generated by Django 5.0.6 on 2024-07-06 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_carmodel_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('UAH', 'UAH')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='exchange_rate_eur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='exchange_rate_uah',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='exchange_rate_usd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='price_eur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='price_uah',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='price_usd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('Honda', 'Honda'), ('Ford', 'Ford'), ('Chevrolet', 'Chevrolet'), ('BMW', 'Bmw'), ('Mercedes-Benz', 'Mercedesbenz'), ('Audi', 'Audi'), ('Volkswagen', 'Volkswagen'), ('Nissan', 'Nissan'), ('Hyundai', 'Hyundai'), ('Kia', 'Kia'), ('Subaru', 'Subaru'), ('Mazda', 'Mazda'), ('Jeep', 'Jeep'), ('Lexus', 'Lexus'), ('Dodge', 'Dodge'), ('Tesla', 'Tesla'), ('Volvo', 'Volvo'), ('Porsche', 'Porsche'), ('Land Rover', 'Landrover')], max_length=20, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
