# Generated by Django 5.0.6 on 2024-07-06 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carmodel_currency_carmodel_exchange_rate_eur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='mileage',
            field=models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='body_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='drive',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='fuel',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='gearbox',
            field=models.CharField(max_length=23),
        ),
    ]
