# Generated by Django 5.0.6 on 2024-07-06 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carmodel_mileage_alter_carmodel_body_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='body_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Station', 'Station'), ('Wagon', 'Wagon'), ('Coupe', 'Coupe'), ('Convertibl', 'Convertible'), ('Roadster', 'Roadster'), ('Crossover', 'Crossover'), ('SUV', 'Suv'), ('Pickup', 'Pickup'), ('Truck', 'Truck'), ('Van', 'Van'), ('Minivan', 'Minivan'), ('Limousine', 'Limousine'), ('Fastback', 'Fastback'), ('Liftback', 'Liftback')], max_length=20),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='engine',
            field=models.FloatField(validators=[django.core.validators.MinLengthValidator(0.1)]),
        ),
    ]
