# Generated by Django 5.0.6 on 2024-07-06 23:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_carmodel_body_type_alter_carmodel_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='drive',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='fuel',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='gearbox',
            field=models.CharField(max_length=23, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
