# Generated by Django 5.0.6 on 2024-07-02 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='age',
            field=models.IntegerField(default=18, validators=[django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='phone',
            field=models.CharField(default=380950233495, max_length=30, validators=[django.core.validators.RegexValidator('^\\+380(50|63|66|67|68|91|92|93|94|95|96|97|98|99)\\d{7}$', ['Номер телефону має починатись з +380', 'Номер телефону має містити код телефонного оператору України 50|63|66|67|68|91|92|93|94|95|96|97|98|99', 'Номер телефону має бути не більшим за 13 символів '])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
