# Generated by Django 5.0.6 on 2024-07-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profilemodel_age_profilemodel_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('manager', 'Manager'), ('admin', 'Admin')], default='buyer', max_length=10),
        ),
    ]
