# Generated by Django 5.0.6 on 2024-07-07 18:51

from django.db import migrations, models

import core.services.upload_avatar


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profilemodel_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.services.upload_avatar.upload_avatar),
        ),
    ]
