# Generated by Django 5.0.6 on 2024-07-06 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_advertviewsmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertmodel',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='advertmodel',
            name='region',
            field=models.CharField(choices=[('Vinnytsia region', 'Vinnytsia'), ('Volyn region', 'Volyn'), ('Dnipropetrovsk region', 'Dnipropetrovsk'), ('Donetsk region', 'Donetsk'), ('Zhytomyr region', 'Zhytomyr'), ('Zakarpattia region', 'Zakarpattia'), ('Zaporizhzhia region', 'Zaporizhzhia'), ('Ivano-Frankivsk region', 'Ivano Frankivsk'), ('Kyiv region', 'Kyiv'), ('Kirovohrad region', 'Kirovohrad'), ('Luhansk region', 'Luhansk'), ('Lviv region', 'Lviv'), ('Mykolaiv region', 'Mykolaiv'), ('Odesa region', 'Odesa'), ('Poltava region', 'Poltava'), ('Rivne region', 'Rivne'), ('Sumy region', 'Sumy'), ('Ternopil region', 'Ternopil'), ('Kharkiv region', 'Kharkiv'), ('Kherson region', 'Kherson'), ('Khmelnytskyi region', 'Khmelnytskyi'), ('Cherkasy region', 'Cherkasy'), ('Chernivtsi region', 'Chernivtsi'), ('Chernihiv region', 'Chernihiv'), ('Autonomous Republic of Crimea', 'Crimea')], max_length=50, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
