# Generated by Django 5.0.6 on 2024-07-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0003_alter_advertmodel_options_alter_advertmodel_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertmodel',
            name='car_photo',
            field=models.ImageField(blank=True, null=True, upload_to='car_photo'),
        ),
    ]
