# Generated by Django 5.0.6 on 2024-07-08 20:59

from django.db import migrations, models

import core.services.upload_avatar


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0005_alter_advertmodel_car_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertmodel',
            name='car_photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.services.upload_avatar.upload_car_photo),
        ),
    ]
