# Generated by Django 5.0.6 on 2024-07-07 15:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advert', '0003_alter_advertmodel_options_alter_advertmodel_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealershipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(1)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dealership_user', to=settings.AUTH_USER_MODEL)),
                ('dealership_adverts', models.ManyToManyField(blank=True, related_name='dealership_adverts', to='advert.advertmodel')),
                ('dealership_admins', models.ManyToManyField(blank=True, related_name='dealership_admins', to=settings.AUTH_USER_MODEL)),
                ('dealership_managers', models.ManyToManyField(blank=True, related_name='dealership_managers', to=settings.AUTH_USER_MODEL)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dealerships',
            },
        ),
    ]
