from django.db.models import TextChoices


class RegionChoices(TextChoices):
    VINNYTSIA = 'Vinnytsia region'
    VOLYN = 'Volyn region'
    DNIPROPETROVSK = 'Dnipropetrovsk region'
    DONETSK = 'Donetsk region'
    ZHYTOMYR = 'Zhytomyr region'
    ZAKARPATTIA = 'Zakarpattia region'
    ZAPORIZHZHIA = 'Zaporizhzhia region'
    IVANO_FRANKIVSK = 'Ivano-Frankivsk region'
    KYIV = 'Kyiv region'
    KIROVOHRAD = 'Kirovohrad region'
    LUHANSK = 'Luhansk region'
    LVIV = 'Lviv region'
    MYKOLAIV = 'Mykolaiv region'
    ODESA = 'Odesa region'
    POLTAVA = 'Poltava region'
    RIVNE = 'Rivne region'
    SUMY = 'Sumy region'
    TERNOPIL = 'Ternopil region'
    KHARKIV = 'Kharkiv region'
    KHERSON = 'Kherson region'
    KHMELNYTSKYI = 'Khmelnytskyi region'
    CHERKASY = 'Cherkasy region'
    CHERNIVTSI = 'Chernivtsi region'
    CHERNIHIV = 'Chernihiv region'
    CRIMEA = 'Autonomous Republic of Crimea' 